import type { Metadata } from 'next'
import './globals.scss'
import Header from '@/components/elements/Header/Header'
import Footer from '@/components/elements/Footer/Footer'
import { AppWrapper } from '@/context/user'
import QueryProvider from '@/queryClient/Provider'
import { ToastContainer } from 'react-toastify'
import 'react-toastify/dist/ReactToastify.css'

export const metadata: Metadata = {
  title: 'TasteEat',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
        <AppWrapper>
          <QueryProvider>
            <Header />
            <main className="container">{children}</main>
            <Footer />
            <ToastContainer />
          </QueryProvider>
        </AppWrapper>
      </body>
    </html>
  )
}
